"""Add column email and pass_secure

Revision ID: 40708aac8d4f
Revises: f6c63c61b4cd
Create Date: 2021-04-26 07:08:18.482728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40708aac8d4f'
down_revision = 'f6c63c61b4cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
